[package]
name = "pore-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
nc-pore-application = { package = "nc-pore-application", path = "../application" }
nc-pore-core = { package = "core", path = "../core" }
nc-pore-infrastructure = { package = "infrastructure", path = "../infrastructure" }
recorder = { path = "../recorder" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "pore-runtime"
path = "src/main.rs"
